INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('A Cultural Exchange Service, Inc.','ACES','https://dealwithaces.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Alliance Abroad Group, L.P.','Alliance Abroad','http://www.allianceabroad.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Australian Association','American Australian Association','http://www.americanaustralian.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Camp And Work Experience','ACAWE','https://acawe.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Exchange Organization, Inc.','AmerEx','http://www.amerex.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Hospitality Academy','AHA','http://www.americanhospitalityacademy.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Institute For Foreign Study - Campower Program','AIFS','https://www.aifs.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Pool Enterprises, Inc.','American Pool','http://americanpool.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Work Adventures, Inc.','AWA','http://americanworkadventures.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('American Work Experience','AWE','http://www.aweusa.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('ASSE International, Inc','ASSE','https://asse.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Camp Counselors USA/Work Experience USA','CCUSA','http://www.ccusa.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Camp Wayne for Boys','Camp Wayne','https://www.campwayne.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('CampGroup, LLC','CAMPGROUP','http://www.campgroup.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('CCI Greenheart','CCI','https://www.cci-exchange.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('CENET Cultural Exchange Network','CENET','http://www.culturalexchangenetwork.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Center for International Career Development','CICD','https://www.cicdgo.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Council on International Educational Exchange','CIEE','https://www.ciee.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('CSB International, Inc.','CSB','http://www.csb-usa.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Cultural Homestay International','CHI','https://www.chinet.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Dynamic Global Exchange, Inc.','Dynamic Global Exchange','http://www.dynamicglobalexchange.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Educational Resource Development Trust','ERDT / SHARE!','http://www.erdtshare.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('GeoVisions','GeoVisions','http://geovisions.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Global Educational Concepts, Inc.','GEC','https://www.globaledconcepts.com/login?returnUrl=%2F');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Greenwood Lake Gaelic Cultural Society, Inc.','Greenwood Lake Gaelic Cultural Society','https://sites.google.com/site/gwlgcs/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('ICEPWORLD, USA','ICEPWORLD','http://www.icepworld.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('InterExchange,Inc.','InterExchange','https://www.interexchange.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('International Cultural Exchange Organization Inc.','ICEO','http://www.iceoinc.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('International Culture and Career Exchange, Inc.','ICCE','http://www.icceusa.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('International Educational Exchange, Inc.','IEE','http://www.ieexchanges.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('International Exchange of North America, Inc.','IENA','https://www.iena.org/wapps/user/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Intrax Work/Travel','Intrax','http://www.intraxworktravel.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Ireland Institute of Pittsburgh','IIOfPitt','http://www.iiofpitt.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Janus International Hospitality Student Exchange','Janus International','http://www.janus-international.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Experience','Life Adventures','http://www.lifeadventures.us/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Signature Services Corporation','Signatures Services','http://www.signatureservices.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Spirit Cultural Exchange','SPIRIT','https://www.spiritexchange.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('The foundation for Worldwide International Student exchange','WISE','http://wise.wisefoundation.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('United Studies, Inc.','USSE','https://www.linkedin.com/company/united-studies-inc-student-exchange');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('University of Louisville','Louisville','http://louisville.edu/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Walt Disney World','Disney','https://jobs.disneycareers.com/international-programs');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('World Wide Cultural Exchange, Inc.','WWCE','https://www.wwceusa.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Viking Cultural Exchange','Viking','http://vikingtravel.hr/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Karavan Travel ','Karavan Travel','http://karavantravel.org/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('BHV Education','BHV','http://www.bhvedu.com/programs_work.php#');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Suncana vura','Suncana vura','http://www.suncana-vura.hr/site/stranice/suncana/HR_kontakt.php?lang=HR&vi=F');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Work and Travel Company','WTC','https://www.worktravelcompany.com/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Experience','Experience','http://www.experience.edu.rs/kontakt/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('STA Travel','STA Travel','http://www.statravel.co.uk/contact_us.htm?WT.ac=topheader-contactus');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Student Exchange Australia New Zealand','Student Exchange Australia New Zealand','http://workandtravelusa.com.au/contact-us/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('United Work and Travel ','United Work and Travel ','http://unitedworkandtravel.com/contact/');
INSERT INTO swtsponsor (full_name,short_name,website_url) VALUES ('Work & Travel USA','Work & Travel USA','http://www.work-and-travel-usa.de/allgemeine-informationen');